name: Update README cards

on:
  schedule:
    - cron: "20 2 * * *"
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Generate top languages card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=donut&theme=dracula&hide_border=true&bg_color=80808008&size_weight=0.75&count_weight=0.25&langs_count=5
          path: assets/stats/languages.svg
          token: ${{ secrets.PROFILE_READ_TOKEN }}

      - name: Generate pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=streamlet&theme=dracula&hide_border=true&bg_color=80808008
          path: assets/stats/streamlet.svg
          token: ${{ secrets.PROFILE_READ_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "horvatda@proton.me"
          git add assets/stats/*.svg
          git commit -m "[automatic] update statistics" || exit 0
          git push
